//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject_Online_floral_delivery.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Eproject_FloralEntities : DbContext
    {
        public Eproject_FloralEntities()
            : base("name=Eproject_FloralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_city> tbl_city { get; set; }
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_district> tbl_district { get; set; }
        public virtual DbSet<tbl_message> tbl_message { get; set; }
        public virtual DbSet<tbl_messageCategory> tbl_messageCategory { get; set; }
        public virtual DbSet<tbl_order> tbl_order { get; set; }
        public virtual DbSet<tbl_orderDetail> tbl_orderDetail { get; set; }
        public virtual DbSet<tbl_paymentType> tbl_paymentType { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<tbl_roles> tbl_roles { get; set; }
        public virtual DbSet<tbl_shippingType> tbl_shippingType { get; set; }
        public virtual DbSet<tbl_imageList> tbl_imageList { get; set; }
    }
}
