//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject_Online_floral_delivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_product()
        {
            this.tbl_orderDetail = new HashSet<tbl_orderDetail>();
            this.tbl_imageList = new HashSet<tbl_imageList>();
        }
    
        public long productID { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> priceSale { get; set; }
        public Nullable<System.DateTime> dayStartSale { get; set; }
        public Nullable<System.DateTime> dayEndSale { get; set; }
        public string image { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isFeatured { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> quantity { get; set; }
        public string metaTitle { get; set; }
        public string description { get; set; }
        public string metaKeyword { get; set; }
        public Nullable<int> countView { get; set; }
        public long categoryID { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orderDetail> tbl_orderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_imageList> tbl_imageList { get; set; }
    }
}
