//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject_Online_floral_delivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.tbl_orderDetail = new HashSet<tbl_orderDetail>();
        }
    
        public long orderID { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> dateOfStart { get; set; }
        public Nullable<System.DateTime> dateOffinish { get; set; }
        public Nullable<bool> status { get; set; }
        public long shippingTypeID { get; set; }
        public long customerID { get; set; }
        public Nullable<double> promotionPrice { get; set; }
        public long paymentTypeID { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_paymentType tbl_paymentType { get; set; }
        public virtual tbl_shippingType tbl_shippingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orderDetail> tbl_orderDetail { get; set; }
    }
}
