//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject_Online_floral_delivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderDetail
    {
        public long orderDetailID { get; set; }
        public long productID { get; set; }
        public long messageID { get; set; }
        public long districtID { get; set; }
        public long orderID { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public string address { get; set; }
        public string note { get; set; }
        public string phone { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual tbl_district tbl_district { get; set; }
        public virtual tbl_message tbl_message { get; set; }
        public virtual tbl_order tbl_order { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
