//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject_Online_floral_delivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_imageList
    {
        public long imageListID { get; set; }
        public string name { get; set; }
        public string extendsion { get; set; }
        public long productID { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
    }
}
